### ISSUE TITLE
move code from folder "loopback-tutor-intern-26" into root of this repository

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/loopback-tutor-intern-26#9]

**Comment by LizTW** [comment]
Ok I followed your directions but I'm getting a fatal error...

![screen shot 2018-06-18 at 8 27 57 pm](https://user-images.githubusercontent.com/30632806/41549215-27c5502a-7336-11e8-9c72-504ec6bf314f.png)

**Comment by atherdon** [comment]
you trying to use my local PC path.
please open your terminal and navigate to your local folder where you have your code. and run 
``` npm run start ``` there

**Comment by atherdon** [comment]
I assume that you're opened your main folder in terminal(based on screenshot)
So put this;
``` 
cd loopback-tutor-intern-26 
npm run start
```
And i think it'll work

**Comment by LizTW** [comment]
And it works!  Thank you!  Sorry - sometimes I struggle in the process and I appreciate the help!

**Comment by atherdon** [comment]
it's ok - setup a new project is usually a big pain in the ass :)
when i only apply to work as developer - i broke my OS 4 times before i
setup my project well. i think your Mac is working fine - so all is fine
